# Use this file to configure the Overcommit hooks you wish to use. This will
# extend the default configuration defined in:
# https://github.com/sds/overcommit/blob/master/config/default.yml
#
# At the topmost level of this YAML file is a key representing type of hook
# being run (e.g. pre-commit, commit-msg, etc.). Within each type you can
# customize each hook, such as whether to only run it on certain files (via
# `include`), whether to only display output if it fails (via `quiet`), etc.
#
# For a complete list of hooks, see:
# https://github.com/sds/overcommit/tree/master/lib/overcommit/hook
#
# For a complete list of options that you can use to customize hooks, see:
# https://github.com/sds/overcommit#configuration
#
# Uncomment the following lines to make the configuration take effect.

CommitMsg:
  CapitalizedSubject:
    enabled: false
  EmptyMessage:
    enabled: true
  GerritChangeId:
    enabled: false
  HardTabs:
    enabled: false
  MessageFormat:
    enabled: true
    pattern: ':.*?: (([A-z].+)\-([0-9].+):.+)|(Merge .+)'
    expected_pattern_message: ":gitmoji: <XXXX-1111>: <Message Subject>"
    sample_message: ":sparkles: TICKET-123: Add overcommit to project"
  RussianNovel:
    enabled: true
  SingleLineSubject:
    enabled: true
  SpellCheck:
    enabled: false
  TextWidth:
    enabled: false
  TrailingPeriod:
    enabled: false
PreCommit:
  AuthorEmail:
    enabled: true
  AuthorName:
    enabled: true
  BrokenSymLinks:
    enabled: true
  CaseConflicts:
    enabled: true
  ForbiddenBranches:
    enabled: true
    branch_patterns:
      - main
  MergeConflicts:
    enabled: true
  Rubocop:
    command: ["rubocop"]
    enabled: true
PrepareCommitMsg:
  CustomScript:
    enabled: true
    required_executable: "bin/hooks/prepare-commit-msg"
PrePush:
  Brakeman:
    command: ["bundle", "exec", "brakeman"]
    enabled: true
  RSpec:
    command: ["bundle", "exec", "rspec"]
    enabled: true
  Cucumber:
    command: ["bundle", "exec", "cucumber"]
    enabled: true
